# Generated by Django 5.0.7 on 2024-07-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('customerBin', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('utmMedim', models.TextField(blank=True, null=True)),
                ('utmTerm', models.TextField(blank=True, null=True)),
                ('utmContent', models.TextField(blank=True, null=True)),
                ('utmCampaign', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
