# Generated by Django 4.2.14 on 2024-07-29 04:38

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingcounter',
            name='city',
        ),
        migrations.RemoveField(
            model_name='marketingcounter',
            name='customerBin',
        ),
        migrations.RemoveField(
            model_name='marketingcounter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='marketingcounter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='marketingcounter',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='marketingcounter',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='marketingcounter',
            name='url',
        ),
        migrations.RemoveField(
            model_name='marketingcounter',
            name='utmCampaign',
        ),
        migrations.RemoveField(
            model_name='marketingcounter',
            name='utmContent',
        ),
        migrations.RemoveField(
            model_name='marketingcounter',
            name='utmMedim',
        ),
        migrations.RemoveField(
            model_name='marketingcounter',
            name='utmTerm',
        ),
        migrations.AddField(
            model_name='marketingcounter',
            name='sensitive_data',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True)),
        ),
    ]
