# Generated by Django 4.2.14 on 2024-07-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_remove_marketingcounter_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcounter',
            name='foo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
