# Generated by Django 4.2.14 on 2024-07-29 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counter', '0003_marketingcounter_foo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingcounter',
            name='foo',
        ),
        migrations.RemoveField(
            model_name='marketingcounter',
            name='sensitive_data',
        ),
        migrations.AddField(
            model_name='marketingcounter',
            name='city',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True)),
        ),
        migrations.AddField(
            model_name='marketingcounter',
            name='customerBin',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True)),
        ),
        migrations.AddField(
            model_name='marketingcounter',
            name='email',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True)),
        ),
        migrations.AddField(
            model_name='marketingcounter',
            name='name',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True)),
        ),
        migrations.AddField(
            model_name='marketingcounter',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketingcounter',
            name='phone',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True)),
        ),
        migrations.AddField(
            model_name='marketingcounter',
            name='subject',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AddField(
            model_name='marketingcounter',
            name='url',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AddField(
            model_name='marketingcounter',
            name='utmCampaign',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AddField(
            model_name='marketingcounter',
            name='utmContent',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AddField(
            model_name='marketingcounter',
            name='utmMedium',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AddField(
            model_name='marketingcounter',
            name='utmSource',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AddField(
            model_name='marketingcounter',
            name='utmTerm',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
    ]
