services:
  mysql-db:
    image: mysql:5.7
    container_name: local-mysql-1
    restart: always
    env_file:
      - ../../.env
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ../.. # Путь к корню проекта
      dockerfile: compose/local/Dockerfile
    container_name: local-backend-web-1
    ports:
      - '80:8000'
    depends_on:
      - mysql-db
    env_file:
      - ../../.env

volumes:
  mysql-data:
