version: '3.8'

services:
  backend-web:
    build:
      context: ../.. # Путь к корню проекта
      dockerfile: compose/local/Dockerfile
    volumes:
      - ../../backend:/app
    ports:
      - '8000:8000'
    env_file:
      - ../../env.local
