services:

  backend:
    build:
      context: ../..
      dockerfile: compose/local/Dockerfile
    container_name: local-backend-web-1
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - ../../.env.local

volumes:
  mysql-data:
