services:
  mysql-db:
    container_name: mysql-container
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=caching_sha2_password
    env_file:
      - ../../.env.prod
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    container_name: django-web
    build:
      context: ../..
      dockerfile: compose/prod/Dockerfile
    restart: always
    env_file:
      - ../../.env.prod
    expose:
      - "8000"
    depends_on:
      - mysql-db
    links:
      - mysql-db
    volumes:
      - static_volume:/app/staticfiles

  nginx:
    container_name: nginx-container
    image: nginx:1.27.0-alpine-slim
    volumes:
      - ../../compose/prod/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  mysql-data:
  static_volume:
